-------ROLES------------

Create table roles(
role_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1  PRIMARY KEY,
role_name VARCHAR2( 255 ) NOT NULL
)
----------ADMINS-USERS----------------
Create table admins(
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    first_name VARCHAR2( 255 ) NOT NULL,
    last_name VARCHAR2( 255 ) NOT NULL,
    user_name VARCHAR2( 255 ) NOT NULL,
    password VARCHAR2( 255 ) NOT NULL,
    image VARCHAR2( 255 ) ,
    role_id number NOT NULL,
     CONSTRAINT fk_roles_admins
      FOREIGN KEY( role_id )
      REFERENCES roles( role_id ) 
      ON DELETE SET NULL
    

)
-------CATEGORIES--------
Create Table categories(
  cate_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
  cate_name VARCHAR2(255) NOT NULL
)
DELETE FROM categories;
-------PRODUCTS--------
create table products(
 product_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
 product_name VARCHAR2(255) NOT NULL,
 description VARCHAR2(max) NOT NULL,
 current_quantity INTEGER NOT NULL,
 cost FLOAT NOT NULL,
 sale FLOAT NOT NULL,
 image VARCHAR2(255) ,
 cate_id NUMBER NOT NULL,
 CONSTRAINT fk_categories_products
      FOREIGN KEY( cate_id )
      REFERENCES categories(cate_id) 
      ON DELETE SET NULL
)
-------CUSTOMERS------------
Create table customers(
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    first_name VARCHAR2( 255 ) NOT NULL,
    last_name VARCHAR2( 255 ) NOT NULL,
    user_name VARCHAR2( 255 ) NOT NULL,
    password VARCHAR2( 255 ) NOT NULL,
    image VARCHAR2( 255 ) ,
    phone_number VARCHAR2(255) ,
    address VARCHAR2(255),
    role_id number NOT NULL,
    city_id number NOT NULL,
     CONSTRAINT fk_roles_customers
      FOREIGN KEY( role_id )
      REFERENCES roles( role_id ) 
      ON DELETE SET NULL ,
       CONSTRAINT fk_cities_customers
      FOREIGN KEY( city_id )
      REFERENCES cities( city_id ) 
      ON DELETE SET NULL 
)




---------ORDERS--------------
Create Table orders(
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
  note VARCHAR2(255) NOT NULL,
  total_price Float,
  shipping_fee Float,
  tax_fee Float,
  status VARCHAR2(255) NOT NULL,
  delivery_date DATE,
  order_date DATE,
    customer_id number NOT NULL,
     CONSTRAINT fk_order_customers
      FOREIGN KEY( customer_id )
      REFERENCES customers( customer_id ) 
      ON DELETE SET NULL 
)
---------ORDERS DETAILS-------
Create Table order_detail(
  order_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
  total_quantily int,
  total_price float,
    product_id number NOT NULL,
     CONSTRAINT fk_order_detail_products
      FOREIGN KEY( product_id )
      REFERENCES products( product_id ) 
      ON DELETE SET NULL 
)
Create Table cities(
city_id  NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
city_name VARCHAR2(255),
 country_id NUMBER,
    CONSTRAINT fk_country_id FOREIGN KEY (country_id) REFERENCES country(country_id)
)
Create Table country(
country_id  NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
country_name VARCHAR2(255)
)
ALTER TABLE cities
ADD country_id NUMBER;

ALTER TABLE cities
ADD CONSTRAINT fk_country_id
FOREIGN KEY (country_id)
REFERENCES country(country_id);

--------------------------------------------
Drop Table cities

CREATE SEQUENCE AUTO_INCREMENT_SEQUENCESTART WITH 1 INCREMENT BY 1;


INSERT INTO roles(name) VALUES ('ADMIN');
INSERT INTO roles(name) VALUES ('EMPLOYEE');

select * from roles;
select * from admins;
----======================
CREATE SEQUENCE product_id_seq
  START WITH 1
  INCREMENT BY 1;

---=====================
CREATE OR REPLACE TRIGGER products_trigger
BEFORE INSERT ON products
FOR EACH ROW
BEGIN
  SELECT product_id_seq.NEXTVAL
  INTO :new.product_id
  FROM dual;
END;
--=============
ALTER TABLE products ADD image VARCHAR2;
---================
CREATE TABLE shopping_cart
(
    shopping_cart_id  NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    total_item INT,
    total_price FLOAT,
    customer_id NUMBER,
    CONSTRAINT fk_shopping_cart_customers
      FOREIGN KEY(customer_id)
      REFERENCES customers(customer_id) 
      ON DELETE SET NULL
);

--===
Create Table cart_items
(
id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
quantity int,
total_price FLOAT,
unit_price FLOAT,
shopping_cart_id number ,
product_id number ,
     CONSTRAINT fk_shopping_cart_cart_item
      FOREIGN KEY( shopping_cart_id )
      REFERENCES shopping_cart( shopping_cart_id ) 
      ON DELETE SET NULL ,
    CONSTRAINT fk_cart_item_products
      FOREIGN KEY( product_id )
      REFERENCES products( product_id ) 
      ON DELETE SET NULL 
)
--==
ALTER TABLE order_detail
ADD  order_id number;
--====
ALTER TABLE order_detail
ADD CONSTRAINT fk_order_order_details
FOREIGN KEY (order_id)
REFERENCES orders(order_id)
ON DELETE SET NULL;



Drop table CUSTOMER;
